const LOGIN = 'LOGIN';
const FETCH_SUCCESS = 'FETCH_SUCCESS'; // fetch do currencies
const FETCH_ERR = 'FETCH_ERR'; // fetch do currencies
const TYPE_EXPENSES = 'TYPE_EXPENSES';
const FETCH_EXPENSES_ERR = 'FETCH_EXPENSES_ERR';

export { LOGIN, FETCH_SUCCESS, FETCH_ERR, TYPE_EXPENSES, FETCH_EXPENSES_ERR };
